config/routes.rb
Rails.application.routes.draw do
  
  root :to => "static_pages#root"
    
  resources :users, :only => [:new, :create]
  resource :session, :only => [:create, :destroy, :new]

  
  # resources :pets do
  #   resources :pet_rental_requests do
  #     member do
  #       post 'respond'
  #     end
  #   end
  # end
    
  
  namespace :api, defaults: { format: :json } do
    resources :pets 
    resources :pet_rental_requests
    resources :images
  end
  
  get '/about', :to => 'static_pages#about', as: :about_page
  get '/contact', :to => 'static_pages#contact', as: :contact_page
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password
  validates :password_digest, :presence => true
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :presence => true, :uniqueness => true
  validates :username, :presence => true, :uniqueness => true

  has_many(
    :pets,
    class_name: "Pet",
    foreign_key: :owner_id,
    primary_key: :id
  )
  
  has_many(
    :pet_rental_requests,
    class_name: "PetRentalRequest",
    foreign_key: :requester_id,
    primary_key: :id
  )

  before_validation :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end

  def password=(unencrypted_password)
    if unencrypted_password.present?
      @password = unencrypted_password
      self.password_digest = BCrypt::Password.create(unencrypted_password)
    end
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, :only => [:show]
  before_action :require_signed_out!, :only => [:create, :new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if params.include?(:id)
      @user = User.find(params[:id])
    else
      redirect_to user_url(current_user)
    end
  end

  def index
  end
  
  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<%if signed_in?%>
  <% redirect_to current_user_url%>
<%else%> 

<div class= "sign-up-page">
<div class="sign-up">
<form action="<%= users_url %>"
      method="post"
      role="form"
      id="sign-up">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text"
     Placeholder="username"
     class="myclass">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password"
     Placeholder="password"
     class="myclass">
  <br>

  <button type="submit" class="btn btn-success" role="button" id="sign-up-button">Sign Up</button>
</form>



 <form action="<%= session_url %>"
      method="post"
      role="form"
      id="sign-in-guest">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <input name="user[username]" type="hidden" value="guestlogin">
  <input name="user[password]" type="hidden" value="guestlogin">
  <button type="submit" class="btn btn-primary" role="button" id="sign-in-guest-button">Guest Demo</button>
</form>
  <div class="sign-up-footer">
      Already a user?<a href="<%= new_session_url %>"> Sign In </a>
  </div>
</div>
</div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>

<%= link_to "Upload a new Pet", new_pet_url %>
<%= link_to "View all pets", pets_url %>