config/routes.rb
Rails.application.routes.draw do
  
  root :to => "static_pages#root"
    
  resources :users, :only => [:new, :create]
  resource :session, :only => [:create, :destroy, :new]

  
  # resources :pets do
  #   resources :pet_rental_requests do
  #     member do
  #       post 'respond'
  #     end
  #   end
  # end
    
  
  namespace :api, defaults: { format: :json } do
    resources :pets 
    resources :pet_rental_requests
    resources :images
  end
  
  get '/about', :to => 'static_pages#about', as: :about_page
  get '/contact', :to => 'static_pages#contact', as: :contact_page
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <div class="col-xs-2 col-xs-offset-4">      
        <p><a href="">Privacy Policy</a></p>
        <p><a href="">Terms and Conditions</a></p>
        <p><a href=""> @ Copyright Policy</a></p> 
    </div>
    <div class="col-xs-2">      
        <p><a href="">Home</a></p>
        <p><a href="">About</a></p>
        <p><a href="">Contact</a></p>
    </div>
    <div class="col-xs-2">      
        <p><a href="">Press</a></p>
        <p><a href="">Blog</a></p>
        <p><a href="">Invite a Friend</a></p> 
    </div>
    
    <div class="social-media">      
        <p>Follow Us!</p>
          <span><i class= "fa fa-twitter-square"></i></span>
          <span><i class= "fa fa-facebook-square"></i></span>
          <i class= "fa fa-google-plus-square"></i>
          <i class= "fa fa-google-plus-square"></i>
          <i class= "fa fa-github-square"></i>
          <i class= "fa fa-pinterest-square"></i>
          <i class= "fa fa-linkedin-square"></i>
          <i class= "fa fa-tumblr-square"></i>

        </ul>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container container-fluid">

    <!-- the dropdown that appears when page is crunched (i.e on mobile)-->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/#"><i class=" glyphicon glyphicon-home"></i> RentMyPet</a>
    </div>

    <!-- main navbar on top of page-->
    <div class="collapse navbar-collapse pull-left" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav nav-pills nav-links">
        <li><a href="/contact" id="contact-link">Contact</a></li>
        <li><a href="/about" id="about-us-link">About Us</a></li>
        <li><a href="/#" id="rent-a-cat-link" class="active">Rent a Pet</a></li>
        <li><a href="/#pets/new" id="rent-a-cat-link">Upload your Pet</a></li>
      </ul>
    </div>
    <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
      <% if signed_in? %>
      <!-- dropdown button-->
      <div class="dropdown pull-right">
        <button class="btn btn-primary dropdown-toggle user-drop-down"
                type="button"
                id="user-drop-down"
                data-toggle="dropdown">
                <%= current_user.username %>
                <span class="caret"></span>
        </button>

        <!-- items in the dropdown-->
        <ul class="dropdown-menu"
            role="menu"
            aria-labelledby="dropdownMenu1">
          <li>
            <a href="<%# user_url(current_user)%>" id="my-profile-link">
              <i class="glyphicon glyphicon-user"></i> My Profile
            </a>
          <li>
            <%= link_to "Sign out", session_url, method: :delete %>
          </li>
        </ul>
      </div>
      <% else %>
      <ul class="nav navbar-nav">
        <li><button class="btn btn-link" id="navbar-sign-in" data-toggle="modal" data-target="#myModal">Sign In</li>
        <li><button class="btn btn-link" id="navbar-sign-up" data-toggle="modal" data-target="#signUpModal">Sign Up</li>
        <!-- <li><%= link_to "Sign in", new_session_url %></li>
        <li><%= link_to "Sign up", new_user_url %></li> -->
      </ul>
      <% end %>
    </div>
  </div>
</nav>

<% if flash[:errors] %>
  <div class="alert alert-warning alert-dismissible" role="alert">
     <button type="button"
             class="close"
             data-dismiss="alert">
             <span aria-hidden="true">&times;</span>
             <span class="sr-only">Close</span>
     </button>
     <%= flash[:errors].join("<br>").html_safe %>
  </div>
<% end %>


<script>
 $(function() {
  $('body').on('click', '.modal-backdrop', function() { $('#myModal').modal("hide") });
  $('body').on('click', '.modal-backdrop', function() { $('#signUpModal').modal("hide") });
 });
 </script>

app/views/layouts/_modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1"  role="dialog">      
  <div class="modal-body">
    <div class="sign-in">
      <form action="<%= session_url %>"
        method="post"
        role="form"
        id="sign-in">
        <input
        name="authenticity_token"
        type="hidden"
        value="<%= form_authenticity_token %>"> 

        <label for="user_username">Username</label>
        <input
        id="user_username"
        name="user[username]"
        type="text"
        Placeholder="username"
        class="myclass">
        <br>

        <label for="user_password">Password</label>
        <input
        id="user_password"
        name="user[password]"
        type="password"
        Placeholder="password"
        class="myclass">
        <br>
        <button type="submit" class="btn btn-success" role="button" id="sign-in-button">Log In</button>
      </form>
          
          
      <form action="<%= session_url %>"
        method="post"
        role="form"
        id="sign-in-guest">
        <input
        name="authenticity_token"
        type="hidden"
        value="<%= form_authenticity_token %>">

        <input name="user[username]" type="hidden" value="guestuser">
        <input name="user[password]" type="hidden" value="guestuser">
        <button type="submit" class="btn btn-primary" role="button" id="sign-in-guest-button">Guest Demo</button>
      </form>
    </div>

</div>
  <div class="sign-up-footer">
      Not yet a user? <a href="<%= new_user_url %>"> Sign up! </a>
  </div>
</div>

app/views/layouts/_sign_up_modal.html.erb
<!--<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#signUpModal">Launch demo modal</button> -->

<div class="modal fade" id="signUpModal" tabindex="-1"  role="dialog">      
  <div class="modal-body">
    <div class="sign-up">
      <form action="<%= users_url %>"
        method="post"
        role="form"
        id="sign-up">
        <input
        name="authenticity_token"
        type="hidden"
        value="<%= form_authenticity_token %>"> 

        <label for="user_username">Username</label>
        <input
        id="user_username"
        name="user[username]"
        type="text"
        Placeholder="username"
        class="myclass">
        <br>

        <label for="user_password">Password</label>
        <input
        id="user_password"
        name="user[password]"
        type="password"
        Placeholder="password"
        class="myclass">
        <br>
        <button type="submit" class="btn btn-success" role="button" id="sign-up-button">Sign Up</button>
      </form>
          
          
      <form action="<%= session_url %>"
        method="post"
        role="form"
        id="sign-up-guest">
        <input
        name="authenticity_token"
        type="hidden"
        value="<%= form_authenticity_token %>">

        <input name="user[username]" type="hidden" value="guestuser">
        <input name="user[password]" type="hidden" value="guestuser">
        <button type="submit" class="btn btn-primary" role="button" id="sign-in-guest-button">Guest Demo</button>
      </form>
    </div>

</div>
  <div class="sign-up-footer">
      Already a user? <a href="<%= new_session_url %>">Sign In</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= filepicker_js_include_tag %>

<script> 
  $(function(){filepicker.setKey("<%= ENV["FILEPICKER_API_KEY"]%>")}); 
</script>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS_API_KEY"] %>">
  </script>
</head>
<body>
  <%= render partial: "layouts/modal" %>
  <%= render partial: "layouts/sign_up_modal" %>
  <%= render partial: "layouts/header" %>
  <%= yield %>
  <%= render partial: "layouts/footer" %>

</body>

</html>